version: '3'

services:
  app:
    container_name: server-doctor
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.060'
          memory: 50M
    restart: always